[package]
name = "practical-rust-book"
version = "0.1.0"
authors = ["Bastian Gruber <bgruber@twilio.com>"]
edition = "2018"

[dependencies]
warp = "0.3"
parking_lot = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.1.1", features = ["full"] }